version: "3.7"

services:
  node-service:
    image: kacangcian/node-cognixus:1.0
    environment:
      PORT: 5000
    ports:
      - target: 5000
        published: 5000
        mode: ingress
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip
      placement:
        constraints:
          - node.role == manager
